title: Store Framework
tagline: A brand new course on Learning Lab
description: >-
  Learning how to build a store using the Store Framework blocks language,
  powered by VTEX IO.
template:
  name: store-framework
  repo: store-framework-template
preferences:
  - type: dropdown
    name: language
    label: Language
    description: Choose your preferred language.
    options:
      - label: English
        value: en
      - label: Español
        value: es
      - label: Português
        value: pt
before:
  - body: setup.md
    title: Basic configurations
    type: createIssue
steps:
  - title: Basic configurations
    description: Store Framework development prerequisites
    translations:
      es:
        title: Configuraciones básicas
        description: Requisitos previos para desarrollar con Store Framework
      pt:
        title: Configurações básicas
        description: Pré-requisitos para desenvolver com o Store Framework
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: respond
        with: new-issue.md
        issue: 1
        data:
          nextIssue: '2'
      - body: storeframework.md
        title: Store Framework 101
        type: createIssue
  - title: Store Framework 101
    description: Store Framework quick and introductory definitions
    translations:
      es:
        title: Store Framework 101
        description: Definiciones rápidas e introductorias sobre Store Framework
      pt:
        title: Store Framework 101
        description: Definições rápidas e introdutórias sobre o Store Framework.
    event: issues.closed
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: respond
        with: new-issue.md
        issue: 2
        data:
          nextIssue: '3'
      - body: course.md
        title: Course functioning
        type: createIssue
  - title: Course functioning
    description: How to interact with the course
    translations:
      es:
        title: Funcionamiento del curso
        description: Explicando cómo interactuar con el curso
      pt:
        title: Funcionamento do curso
        description: Explicando como interagir com o curso.
    event: issues.closed
    link: '{{ repoUrl }}/issues/3'
    actions:
      - type: respond
        with: new-issue.md
        issue: 3
        data:
          nextIssue: '4'
      - body: helloworld.md
        title: 'Hello, World!'
        type: createIssue
  - title: 'Hello, World!'
    description: Compose and reference your first block in Store Framework
    translations:
      es:
        title: 'Hello, World!'
        description: Componga y haga referencia a su primer bloque en Store Framework
      pt:
        title: 'Hello, World!'
        description: Componha e referencie seu primeiro bloco no Store Framework
    event: status
    link: '{{ repoUrl }}/issues/4'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 4
        data:
          nextIssue: '5'
      - body: infocard.md
        title: 'Info Card: Store Framework''s call to action'
        type: createIssue
  - title: 'Info Card: Store Framework''s call to action'
    description: Defining a block's call to action on our homepage
    translations:
      es:
        title: 'Info Card: el call to action de Store Framework'
        description: Definiremos un bloque call to action en nuestro home
      pt:
        title: 'Info Card: o call to action do Store Framework'
        description: Definiremos um bloco call to action na nossa home
    event: status
    link: '{{ repoUrl }}/issues/5'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 5
        data:
          nextIssue: '6'
      - body: csshandles.md
        title: CSS Handles and the power of customizing blocks
        type: createIssue
  - title: CSS Handles and the power of customizing blocks
    description: Customize the styles of your blocks
    translations:
      es:
        title: CSS Handles y el poder de la personalización de bloques
        description: Personalice el estilo de sus bloques
      pt:
        title: CSS handles e o poder da customização de blocos
        description: Personalize o estilo dos seus blocos
    event: status
    link: '{{ repoUrl }}/issues/6'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 6
        data:
          nextIssue: '7'
      - body: flexlayout.md
        title: 'Flex Layout: create layouts using the power of Flexbox'
        type: createIssue
  - title: 'Flex Layout: create layouts using the power of Flexbox'
    description: Let's create complex layouts in a simple way
    translations:
      es:
        title: 'Flex Layout: cree layouts utilizando el poder de Flexbox'
        description: Creemos layouts complejos de forma sencilla
      pt:
        title: 'Flex Layout: crie layouts utilizando o poder do Flexbox'
        description: Vamos criar layouts complexos de forma simples
    event: status
    link: '{{ repoUrl }}/issues/7'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 7
        data:
          nextIssue: '8'
      - body: shelf.md
        title: Product shelf
        type: createIssue
  - title: Product shelf
    description: How to intuitively display a product window display
    translations:
      es:
        title: Estante de productos
        description: Cómo mostrar una vitrina de productos de forma intuitiva
      pt:
        title: Prateleira de produtos
        description: Como exibir uma vitrine de produtos de forma intuitiva
    event: status
    link: '{{ repoUrl }}/issues/8'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 8
        data:
          nextIssue: '9'
      - body: slider.md
        title: Blocks carousel
        type: createIssue
  - title: Blocks carousel
    description: Insert content into a carousel layout
    translations:
      es:
        title: Carrusel de bloques
        description: Ingrese contenido en un layout de carrusel
      pt:
        title: Carrossel de blocos
        description: Insira conteúdo num layout de carrossel
    event: status
    link: '{{ repoUrl }}/issues/9'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 9
        data:
          nextIssue: '10'
      - body: responsive.md
        title: Making your content responsive
        type: createIssue
  - title: Making your content responsive
    description: Use responsive layout to adapt your content to different devices
    translations:
      es:
        title: Haciendo que su contenido sea responsivo
        description: >-
          Use responsive layout para adaptar su contenido a diferentes
          dispositivos
      pt:
        title: Tornando seu conteúdo responsivo
        description: >-
          Use o responsive layout para adaptar seu conteúdo para diferentes
          dispositivos
    event: status
    link: '{{ repoUrl }}/issues/10'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 10
        data:
          nextIssue: '11'
      - body: pdp.md
        title: Product page
        type: createIssue
  - title: Product page
    description: First steps to creating a product details page
    translations:
      es:
        title: Página de producto
        description: Primeros pasos para crear una página de detalles de producto
      pt:
        title: Página de produto
        description: Primeiros passsos para montar uma página de detalhes de produto
    event: status
    link: '{{ repoUrl }}/issues/11'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 11
        data:
          nextIssue: '12'
      - body: pdp2.md
        title: Evolving your product page (pdp)
        type: createIssue
  - title: Evolving your product page (pdp)
    description: Adding new blocks and making the page more interactive
    translations:
      es:
        title: Evolucionando su página de producto (pdp)
        description: Agregando nuevos bloques y haciendo que la página sea más interactiva
      pt:
        title: Evoluindo sua página de produto (pdp)
        description: Adicionando novos blocos e deixando a página mais interativa
    event: status
    link: '{{ repoUrl }}/issues/12'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 12
        data:
          nextIssue: '13'
      - body: pdp3.md
        title: Finishing your pdp
        type: createIssue
  - title: Finishing your pdp
    description: Using related products and editing properties
    translations:
      es:
        title: Finalizando su pdp
        description: Usando productos relacionados y alterando propiedades
      pt:
        title: Finalizando sua pdp
        description: Usando produtos relacionados e alterando propriedades
    event: status
    link: '{{ repoUrl }}/issues/13'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 13
        data:
          nextIssue: '14'
      - body: search.md
        title: Search page
        type: createIssue
  - title: Search page
    description: Getting to know a search page's blocks
    translations:
      es:
        title: Página de búsqueda
        description: Conociendo los bloques de una página de búsqueda
      pt:
        title: Página de busca
        description: Conhecendo os blocos de uma página de busca
    event: status
    link: '{{ repoUrl }}/issues/14'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 14
        data:
          nextIssue: '15'
      - body: search2.md
        title: Adjusting the search page's layout
        type: createIssue
  - title: Adjusting the search page's layout
    description: Adding lines and columns to improve the search layout
    translations:
      es:
        title: Ajustando layout de página de búsqueda
        description: Agregando líneas y columnas para mejorar el layout de búsqueda
      pt:
        title: Ajustando layout da página de busca
        description: Adicionando linhas e colunas para melhorar o layout da busca
    event: status
    link: '{{ repoUrl }}/issues/15'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 15
        data:
          nextIssue: '16'
      - body: styles.md
        title: Global styles
        type: createIssue
  - title: Global styles
    description: Editing semantic classes to change your store's style
    translations:
      es:
        title: Estilos globales
        description: Altere clases semánticas para cambiar el estilo de su tienda
      pt:
        title: Estilos globais
        description: Altere classes semânticas para mudar o estilo da sua loja
    event: status
    link: '{{ repoUrl }}/issues/16'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 16
        data:
          nextIssue: '17'
      - body: custom-template.md
        title: Creating custom templates
        type: createIssue
  - title: Creating custom templates
    description: Create a path and link a customized template
    translations:
      es:
        title: Creando templates personalizados
        description: Cree una ruta y asocie un template personalizado
      pt:
        title: Criando templates customizados
        description: Crie uma rota e associe um template customizado
    event: status
    link: '{{ repoUrl }}/issues/17'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 17
        data:
          nextIssue: '18'
      - body: tab-layout.md
        title: Tab layout
        type: createIssue
  - title: Tab layout
    description: Using tabs layout on the about us page
    translations:
      es:
        title: Layout de pestañas
        description: Usando layout de pestañas en la página institucional
      pt:
        title: Layout de abas
        description: Usando layout de abas na página institucional
    event: status
    link: '{{ repoUrl }}/issues/18'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 18
        data:
          nextIssue: '19'
      - body: richtextmarkdown.md
        title: Exploring the power behind rich text
        type: createIssue
  - title: Exploring the power behind rich text
    description: Advanced Markdown usage
    translations:
      es:
        title: Explorando el poder de rich text
        description: Usando el lenguaje de Markdown de forma avanzada
      pt:
        title: Explorando o poder do rich text
        description: Usando a linguagem do Markdown de forma avançada
    event: status
    link: '{{ repoUrl }}/issues/19'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 19
        data:
          nextIssue: '20'
      - body: iframe.md
        title: Inserting an Iframe on our about us page
        type: createIssue
  - title: Inserting an Iframe on our about us page
    description: Displaying an Instagram post in your store
    translations:
      es:
        title: Insertando un Iframe en nuestra página institucional
        description: Mostrando una publicación de Instagram en su tienda
      pt:
        title: Inserindo um Iframe na nossa página institucional
        description: Exibindo um post do Instagram na sua loja
    event: status
    link: '{{ repoUrl }}/issues/20'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 20
        data:
          nextIssue: '21'
      - body: landing.md
        title: Building a custom search landing page
        type: createIssue
  - title: Building a custom search landing page
    description: Defining pages for events that have customized products
    translations:
      es:
        title: Construyendo un landing personalizado de búsqueda
        description: Definiendo páginas de eventos con productos personalizados
      pt:
        title: Construindo uma landing customizada de busca
        description: Definindo páginas de eventos com produtos customizados
    event: status
    link: '{{ repoUrl }}/issues/21'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 21
        data:
          nextIssue: '22'
      - body: header.md
        title: Header
        type: createIssue
  - title: Header
    description: Defining header blocks and editing the iconography
    translations:
      es:
        title: Cabecera de la tienda
        description: Definiendo bloques de cabecera y alterando iconografía
      pt:
        title: Cabeçalho da loja
        description: Definindo blocos de cabeçalho e alterando iconografia
    event: status
    link: '{{ repoUrl }}/issues/22'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 22
        data:
          nextIssue: '23'
      - body: menu.md
        title: Menu
        type: createIssue
  - title: Menu
    description: Creating your store's browsing
    translations:
      es:
        title: Menú
        description: Creando la navegación de su tienda
      pt:
        title: Menu
        description: Criando a navegação da sua loja
    event: status
    link: '{{ repoUrl }}/issues/23'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 23
        data:
          nextIssue: '24'
      - body: menu-flex.md
        title: Advanced menu with Flex Layout
        type: createIssue
  - title: Advanced menu with Flex Layout
    description: Enriching the menu with additional blocks
    translations:
      es:
        title: Menú avanzado con Flex Layout
        description: Enriqueciendo el menú con otros bloques
      pt:
        title: Menu avançado com flex layout
        description: Enriquecendo o menu com outros blocos
    event: status
    link: '{{ repoUrl }}/issues/24'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 24
        data:
          nextIssue: '25'
      - body: footer.md
        title: Footer
        type: createIssue
  - title: Footer
    description: Defining footer blocks
    translations:
      es:
        title: Pie de Página
        description: Definiendo bloques de pie de página
      pt:
        title: Rodapé
        description: Definindo blocos de rodapé
    event: status
    link: '{{ repoUrl }}/issues/25'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: congrats_course.md